spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
      host: localhost
      port: 6379
      channels:
        auth-payment:
          request: auth-payment-request
          response: auth-payment-response
        cancel-payment:
          request: cancel-payment-request
          response: cancel-payment-response
        clearing-payment:
          request: clearing-payment-request
          response: clearing-payment-response
        error-payment:
          request: error-payment-request
          response: error-payment-response

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  clearing:
    job:
      interval: 100000

server:
  port: 9080

currency-api:
  url: https://api.exchangeratesapi.io/v1/
  api-key: QN0WSBBHFMfIp45JdHUyuA9gYRfphUi5
  base-currency: EUR
  redis-key: currencyRates
  cron: "00 30 09 * * *"
  timeout:
    connection: 5000
    read: 1000

logging:
  level:
    root: info

retry:
  retry: 5
  delay: 3000