spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
          host: localhost
          port: 6379

server:
  port: 9080

currency-scheduling:
  cron: "0 0 1 * * *"

currency:
  key: 08a9cf90a2931b1ffea4614703e7f54f

logging:
  level:
    root: info